# Generated by Django 5.0.3 on 2024-04-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_per_day_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='package',
        ),
    ]
