# Generated by Django 5.0.3 on 2024-04-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='package',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=0, max_length=30),
        ),
    ]
